// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgdylvhlyxfwlkfhyzxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZHlsdmhseXhmd2xrZmh5enh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDA0NDIsImV4cCI6MjA1OTkxNjQ0Mn0.n_xSarA5uuqcFVnu4i1k-QGJvzXNFY2yYckXL0tH1nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);